icons_format = "{icon}"

[theme]
theme = "srcery"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = "CPU: $usage%"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "Disk: $available.eng(w:2) $icon"

[[block]]
block = "memory"
format = "Memory: $mem_total_used_percents.eng(w:2)% $icon"
format_alt = "Swap: $swap_used_percents.eng(w:2)% $icon_swap"

[[block]]
block = "sound"
format = "Sound: $icon"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%Y-%m-%d %H:%M:%S') $icon"

[[block]]
block = "battery"
format = "%status %percentage $icon"
path = "/sys/class/power_supply/BAT0/uevent"

[[block]]
block = "network_eth0"
format_up = "Eth0: %ip $icon"
format_down = "Eth0: down $icon"
path = "/sys/class/net/eth0/operstate"

[[block]]
block = "network_wlo1"
format_up = "WiFi: %quality $icon"
format_down = "WiFi: down $icon"
path = "/sys/class/net/wlo1/operstate"

[[block]]
block = "load"
format = "Load: %1min $icon"

[[block]]
block = "run_watch"
path = "/var/run/dhclient*.pid"
format = "DHCP $icon"

[[block]]
block = "tztime"
format = "%Y-%m-%d %H:%M:%S $icon"

